include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    argument_type_not_assignable: false
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
